name: 添加比赛
description: 用户提交比赛信息的Issue模板
title: "<添加比赛>"
labels: []
assignees:
  - mcyydscc 
body: 
  - type: input
    id: name
    attributes:
      label: 赛事名称
      placeholder: "DIDCTF"
    validations:
      required: true

  - type: input
    id: link
    attributes:
      label: 比赛官方链接
      placeholder: "https://forensics.didctf.com/"
    validations:
      required: true

  - type: input
    id: type
    attributes:
      label: 团队人数
      description: 请注明人数
      placeholder: "3"
    validations:
      required: true

  - type: input
    id: bmks
    attributes:
      label: 报名开始时间
      description: 格式 yyyy-MM-dd HH:mm:ss
      placeholder: "2024-01-01 00:00:00"
    validations:
      required: true

  - type: input
    id: bmjz
    attributes:
      label: 报名结束时间
      description: 格式 yyyy-MM-dd HH:mm:ss
      placeholder: "2024-01-02 00:00:00"
    validations:
      required: true
  
  - type: input
    id: bsks
    attributes:
      label: 比赛开始时间
      placeholder: "2024-01-03 00:00:00"
    validations:
      required: true

  - type: input
    id: bsjs
    attributes:
      label: 比赛结束时间
      placeholder: "2024-01-04 00:00:00"
    validations:
      required: true
  
  - type: input
    id: qq
    attributes:
      label: 赛事群聊
      description: 填写比赛官方群聊
      placeholder: "123456789"
    validations:
      required: true

  - type: input
    id: other
    attributes:
      label: 备注信息
      placeholder: "无"
    validations:
      required: true
